#define MOTOR_LEFT_PORT 1
#define MOTOR_RIGHT_PORT 4

#define INITIAL_BUGGY_SPEED 100
// #define INITIAL_BUGGY_SPEED 50
#define MOTORS_SPEED_OFFSET 50

#define ROTATION_EPSILON 0.2
#define ROTATION_SPEED 20

#define ROTATION_NEARING_EPSILON 20
#define ROTATION_NEARING_SPEED 10
